-- Create USER_ACCOUNT table

CREATE TABLE user_account
(
    user_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name    VARCHAR(255),
    last_name     VARCHAR(255),
    email_address VARCHAR(255),
    date_created  TIMESTAMP
);