
-- =========================================================
-- USER_ACCOUNT
-- =========================================================
CREATE TABLE user_account
(
    user_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name         VARCHAR(255),
    last_name          VARCHAR(255),
    email_address      VARCHAR(255),
    active             BOOLEAN,

    -- audit columns (AuditingModel + BaseEntity)
    created_by         VARCHAR(255),
    created_date       TIMESTAMP,
    last_modified_date TIMESTAMP,
    last_modified_by   VARCHAR(255),
    version            BIGINT
);

-- =========================================================
-- ROLE
-- =========================================================
CREATE TABLE role
(
    role_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid               VARCHAR(255),
    name               VARCHAR(255),
    description        VARCHAR(255),
    role_type          VARCHAR(50),

    -- audit columns (AuditingModel + BaseEntity)
    created_by         VARCHAR(255),
    created_date       TIMESTAMP,
    last_modified_date TIMESTAMP,
    last_modified_by   VARCHAR(255),
    version            BIGINT
);

-- =========================================================
-- USER_IN_ROLE (join table user_account <-> role)
-- =========================================================
CREATE TABLE user_in_role
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            BIGINT NOT NULL,
    role_id            BIGINT NOT NULL,

    -- audit columns (AuditingModel + BaseEntity)
    created_by         VARCHAR(255),
    created_date       TIMESTAMP,
    last_modified_date TIMESTAMP,
    last_modified_by   VARCHAR(255),
    version            BIGINT,

    CONSTRAINT uq_user_in_role_user_role UNIQUE (user_id, role_id),

    CONSTRAINT fk_user_in_role_user
        FOREIGN KEY (user_id) REFERENCES user_account (user_id),

    CONSTRAINT fk_user_in_role_role
        FOREIGN KEY (role_id) REFERENCES role (role_id)
);